bundler_args: --clean --deployment
sudo: false
cache: bundler
language: ruby
gemfile:
  - Gemfile
  - gemfiles/Gemfile-6.0
  - gemfiles/Gemfile-7.0
  - gemfiles/Gemfile-7.1
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
matrix:
  exclude:
    - rvm: 3.0
      gemfile: gemfiles/Gemfile-6.0
    - rvm: 3.1
      gemfile: gemfiles/Gemfile-6.0
    - rvm: 3.2
      gemfile: gemfiles/Gemfile-6.0
    - rvm: 3.3
      gemfile: gemfiles/Gemfile-6.0
    - rvm: 2.5
      gemfile: gemfiles/Gemfile-7.0
    - rvm: 2.6
      gemfile: gemfiles/Gemfile-7.0
    - rvm: 2.7
      gemfile: gemfiles/Gemfile-7.0
    - rvm: 2.5
      gemfile: gemfiles/Gemfile-7.1
    - rvm: 2.6
      gemfile: gemfiles/Gemfile-7.1
    - rvm: 2.7
      gemfile: gemfiles/Gemfile-7.1
before_script:
  "cd spec/dummy && bundle exec rake db:create && bundle exec rake db:migrate && cd ../.."
after_success:
  - bundle exec codeclimate-test-reporter
